Governance improvements
anoma/spec pull request #67
Opened 2022-03-11 15:10 UTC by Fraccaman

2022-03-15 11:29 UTC, cwgoes requested changes
ACK but see comments

2022-03-15 11:29 UTC, cwgoes commented on src/architecture/m1/governance.md
> +`max_proposal_content_size` tells the maximum number of characters allowed in the proposal content.\
mismatch in names? above you say `max_proposal_content` but I assume these are intended to be the same?

I like this name better though

2022-03-15 11:29 UTC, cwgoes commented on src/architecture/m1/governance.md
> +`min_proposal_grace_epochs` is the minimum required number of `Epoch` between `start_epoch` and `end_epoch`.
what's the difference between this and `min_proposal_period` ?

2022-03-15 11:29 UTC, cwgoes commented on src/architecture/m1/governance.md
> +`min_proposal_grace_epochs` is the minimum required number of `Epoch` between `start_epoch` and `end_epoch`.
what's the difference between this and `min_proposal_period` ?

2022-03-15 11:29 UTC, cwgoes commented on src/architecture/m1/governance.md
> +This is to leverage the `M1T` VP to check that the funds were correctly locked.
this is separate from the treasury balance, right?

2022-03-15 11:29 UTC, cwgoes commented on src/architecture/m1/governance.md
> +The governance subkey, `/$GovernanceAddress/proposal/$id/funds` will be used after the tally step to know the exact amount of tokens to refund/slash.
this isn't slashing - funds from failed proposal deposits should just be sent to the treasury

2022-03-15 11:29 UTC, cwgoes commented on src/architecture/m1/governance.md
> +/$TreasuryAddress/max_spendable_sum: u64
why is this not just `balance` ?

2022-03-15 13:39 UTC, grarco commented on src/architecture/m1/governance.md
> +`min_proposal_grace_epochs` is the minimum required number of `Epoch` between `start_epoch` and `end_epoch`.
The description is wrong, it should be 

```suggestion
`min_proposal_grace_epochs` is the minimum required time window (in `Epoch`) between `end_epoch` and the epoch in which the proposal has to be executed.
```

2022-03-15 13:43 UTC, grarco commented on src/architecture/m1/governance.md
> +This is to leverage the `M1T` VP to check that the funds were correctly locked.
Yes this is a balance where we park funds while we wait to see if the proposal passes: if it does we'll refund, otherwise we'll move the funds from here to the treasury balance

2022-03-15 13:44 UTC, grarco commented on src/architecture/m1/governance.md
> +The governance subkey, `/$GovernanceAddress/proposal/$id/funds` will be used after the tally step to know the exact amount of tokens to refund/slash.
Yes I guess this is a bad choice of words, gonna fix that

2022-03-15 14:44 UTC, cwgoes commented on src/architecture/m1/governance.md
> +/$TreasuryAddress/max_spendable_sum: u64
ah gotcha

2022-03-17 13:21 UTC, cwgoes commented
Please merge/rebase this after the rename (m1 -> namada)

2022-03-23 13:42 UTC, cwgoes approved these changes
ACK, thank you!

2022-03-23 13:43 UTC, merged